name: Matrix limit test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: steps.prepare.outputs.MATRIX
    steps:
      - name: prepare
        id: prepare
        run: |
          echo "MATRIX"="{\"include\":[{\"project\":\"foo\"},{\"project\":\"bar\"}]}" >> "$GITHUB_OUTPUT"   
      - name: echo matrix
        run: echo ${{steps.prepare.outputs.MATRIX}}
      - name: fromJson
        run: ${{fromJson(steps.prepare.outputs.MATRIX}}

  build:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
      max-parallel: 2
    steps:

      - name: Run a one-line script
        run: echo Hello, ${{matrix.work}}

