name: call reusable workflow
on:
  workflow_dispatch:
  push: 
    branches: [main]

jobs:
  call:
    name: call reusable workflow
    uses: belcebus/test-matrix/.github/workflows/called.yml@main
    with:
      max: 4
        
