name: Matrix limit test


on:
  workflow_call:
    inputs:
      max:
        type: number
        required: false
        default: 3
        description: "maximum number of parallel executions"
  
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.prepare.outputs.MATRIX}}
    steps:
      - name: prepare
        id: prepare
        run: |
              json_object="{ \"include\": ["
              for ((i=1; i<=256; i++))
              do
                  json_object+=" { \"work\": \"bar$i\" }"
                  if [ $i -lt 257 ]; then
                      json_object+=","
                  fi
              done
              json_object+=" ] }"
              echo "MATRIX"=$json_object >> "$GITHUB_OUTPUT"   
      - name: echo matrix
        run: echo ${{steps.prepare.outputs.MATRIX}}
      - name: fromJson
        run: echo "${{ fromJson(steps.prepare.outputs.MATRIX) }}"      

  build:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
      max-parallel: ${{ inputs.max }}
    steps:

      - name: Run a one-line script
        run: |
          echo Hello, ${{matrix.work}}
          echo "${{needs.prepare-matrix.outputs.matrix}}"

